language: java
jdk: oraclejdk8
jobs:
  include:
    - stage: unit tests
      script: "Running unit tests (1)"
    - stage: unit tests
      script: "Running unit tests (2)"
    - stage: deploy to staging
      script: skip
      deploy: 
        provider: heroku
        app: sf-stages-staging
        api_key: 19dcaf5a-e3bf-4f55-872c-36c6f4877345
