
sudo: false
language: java
jdk:
  - oraclejdk8
install: true


script:
  - mvn clean install
  - 'make test'
  - 'make build'


deploy:
  provider: heroku
  app: rsoi123
  api_key:
    secure: 19dcaf5a-e3bf-4f55-872c-36c6f4877345


